In [1]:
# importing the basic libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler

In [4]:
# reading data from the file
#Source: http://archive.ics.uci.edu/ml/datasets/SPECTF+Heart

In [4]:
df = pd.read_csv('SPECTF_test.csv')

In [5]:
df.head()

Attr_1  Attr_2  Attr_3  Attr_4  Attr_5  Attr_6  Attr_7  Attr_8  Attr_9  \
0      32      41      76      34      65      53      30      54      16   
1      76      65      60      40      32      34      65      50      53   
2      60      51      75      60      65      45      64      55      55   
3      64      60      71      69      71      65      66      64      68   
4      65      69      66      76      58      67      65      72      66   

   Attr_10  ...  Attr_36  Attr_37  Attr_38  Attr_39  Attr_40  Attr_41  \
0       51  ...       43       67       61       29       31       17   
1       37  ...       51       65       59       43       39       35   
2       61  ...       68       69       63       62       53       57   
3       59  ...       55       66       58       65       65       75   
4       64  ...       64       71       70       72       69       70   

   Attr_42  Attr_43  Attr_44  Class  
0        8       18       11    Yes  
1       30       24       21    Yes  
2       31       46       30    Yes  
3       64       61       56    Yes  
4       65       63       61    Yes  

[5 rows x 45 columns]

In [6]:
df.tail()

Attr_1  Attr_2  Attr_3  Attr_4  Attr_5  Attr_6  Attr_7  Attr_8  Attr_9  \
105      70      75      72      72      67      71      71      78      63   
106      59      57      67      71      66      68      68      70      56   
107      67      64      73      75      77      77      74      70      65   
108      68      65      72      72      47      74      76      74      67   
109      66      54      69      66      69      69      75      72      63   

     Attr_10  ...  Attr_36  Attr_37  Attr_38  Attr_39  Attr_40  Attr_41  \
105       67  ...       67       68       70       70       71       64   
106       62  ...       64       56       53       71       68       64   
107       62  ...       64       65       60       68       75       74   
108       66  ...       69       71       73       73       75       68   
109       62  ...       65       65       64       67       69       71   

     Attr_42  Attr_43  Attr_44  Class  
105       67       56       54     No  
106       63       56       56     No  
107       80       67       68     No  
108       56       58       44     No  
109       68       59       59     No  

[5 rows x 45 columns]

In [86]:
# identifying the number of categories available

In [87]:
y = df['Class'].values

In [88]:
df['Class'].value_counts()

Yes    55
No     55
Name: Class, dtype: int64

In [89]:
# since there are 2 categories we are going to using k = 2.

In [90]:
y.shape

(110,)

In [91]:
X = df.drop(['Class'],axis = 1).values

In [15]:
X[:10]

array([[32, 41, 76, 34, 65, 53, 30, 54, 16, 51, 61, 43, 74, 70, 62, 21,
        34, 42, 61, 37, 58, 66, 54, 49, 17, 19, 11, 42, 53, 30, 71,  9,
        61, 16, 31, 43, 67, 61, 29, 31, 17,  8, 18, 11],
       [76, 65, 60, 40, 32, 34, 65, 50, 53, 37, 66, 53, 33, 31, 30, 30,
        69, 75, 64, 45, 68, 65, 57, 43, 23, 23, 53, 77, 48, 32, 55, 32,
        48, 23, 62, 51, 65, 59, 43, 39, 35, 30, 24, 21],
       [60, 51, 75, 60, 65, 45, 64, 55, 55, 61, 66, 74, 61, 50, 62, 41,
        70, 63, 60, 62, 76, 69, 70, 54, 51, 47, 77, 80, 69, 48, 74, 59,
        72, 57, 76, 68, 69, 63, 62, 53, 57, 31, 46, 30],
       [64, 60, 71, 69, 71, 65, 66, 64, 68, 59, 63, 67, 68, 64, 73, 59,
        73, 60, 72, 56, 77, 68, 69, 69, 66, 59, 57, 40, 55, 53, 69, 63,
        71, 63, 66, 55, 66, 58, 65, 65, 75, 64, 61, 56],
       [65, 69, 66, 76, 58, 67, 65, 72, 66, 64, 77, 75, 64, 62, 63, 59,
        71, 61, 67, 45, 74, 45, 66, 46, 64, 48, 62, 27, 65, 67, 72, 72,
        62, 66, 71, 64, 71, 70, 72, 69, 70, 65, 63, 

In [16]:
# distance calculator
y.size

110

In [18]:
print(X)

[[32 41 76 ...  8 18 11]
 [76 65 60 ... 30 24 21]
 [60 51 75 ... 31 46 30]
 ...
 [67 64 73 ... 80 67 68]
 [68 65 72 ... 56 58 44]
 [66 54 69 ... 68 59 59]]


In [181]:
print(X)

[[32 41 76 ...  8 18 11]
 [76 65 60 ... 30 24 21]
 [60 51 75 ... 31 46 30]
 ...
 [67 64 73 ... 80 67 68]
 [68 65 72 ... 56 58 44]
 [66 54 69 ... 68 59 59]]


In [182]:
# distance between 2 points
def distance(p1,p2):
    
    return np.linalg.norm(p1 - p2)

In [183]:
# calculating centroid 

In [184]:
# centroid of a cluster
def centroid(cluster):
    
    length = cluster.shape[0]
    c = [None]*44
    for i in range(44):
        c[i] = np.sum(cluster[:,i])
        c[i] = c[i]/length
    
    
    # c0, c1, c2, c3 = c0/length , c1/length , c2/length , c3/length 
       
    return np.array(c)


In [185]:
df.head()

Attr_1  Attr_2  Attr_3  Attr_4  Attr_5  Attr_6  Attr_7  Attr_8  Attr_9  \
0      32      41      76      34      65      53      30      54      16   
1      76      65      60      40      32      34      65      50      53   
2      60      51      75      60      65      45      64      55      55   
3      64      60      71      69      71      65      66      64      68   
4      65      69      66      76      58      67      65      72      66   

   Attr_10  ...  Attr_36  Attr_37  Attr_38  Attr_39  Attr_40  Attr_41  \
0       51  ...       43       67       61       29       31       17   
1       37  ...       51       65       59       43       39       35   
2       61  ...       68       69       63       62       53       57   
3       59  ...       55       66       58       65       65       75   
4       64  ...       64       71       70       72       69       70   

   Attr_42  Attr_43  Attr_44  Class  
0        8       18       11    Yes  
1       30       24       21    Yes  
2       31       46       30    Yes  
3       64       61       56    Yes  
4       65       63       61    Yes  

[5 rows x 45 columns]

In [186]:
# Assigning random cluster centers initially

In [420]:
c1 = X[14].copy()
c2 = X[72].copy()
c1 = c1.reshape(1,44)
c2 = c2.reshape(1,44)

In [421]:
# cluster 1

In [422]:
c1

array([[40, 73, 61, 74, 61, 67, 56, 75, 64, 71, 75, 76, 63, 61, 56, 67,
        70, 73, 69, 60, 74, 63, 65, 73, 57, 63, 66, 69, 60, 66, 72, 71,
        57, 64, 64, 69, 67, 68, 59, 66, 55, 62, 51, 60]], dtype=int64)

In [423]:
# cluster 2

In [424]:
c2

array([[59, 68, 69, 67, 69, 59, 78, 73, 66, 65, 77, 73, 74, 66, 66, 55,
        71, 66, 69, 68, 75, 73, 80, 79, 69, 65, 69, 66, 68, 65, 75, 71,
        59, 61, 65, 64, 73, 71, 81, 75, 74, 65, 69, 66]], dtype=int64)

In [425]:
print(X)


[[32 41 76 ...  8 18 11]
 [76 65 60 ... 30 24 21]
 [60 51 75 ... 31 46 30]
 ...
 [67 64 73 ... 80 67 68]
 [68 65 72 ... 56 58 44]
 [66 54 69 ... 68 59 59]]


In [426]:
# centroids for each cluster

In [427]:
centroid_1 = centroid(c1)
centroid_2 = centroid(c2)

In [428]:
centroid_1

array([40., 73., 61., 74., 61., 67., 56., 75., 64., 71., 75., 76., 63.,
       61., 56., 67., 70., 73., 69., 60., 74., 63., 65., 73., 57., 63.,
       66., 69., 60., 66., 72., 71., 57., 64., 64., 69., 67., 68., 59.,
       66., 55., 62., 51., 60.])

In [429]:
centroid_2

array([59., 68., 69., 67., 69., 59., 78., 73., 66., 65., 77., 73., 74.,
       66., 66., 55., 71., 66., 69., 68., 75., 73., 80., 79., 69., 65.,
       69., 66., 68., 65., 75., 71., 59., 61., 65., 64., 73., 71., 81.,
       75., 74., 65., 69., 66.])

In [430]:
# making a numpy array for all the clusters for futher calculations

In [431]:
cluster_centroid = np.array([centroid_1,centroid_2])

In [432]:
cluster_centroid

array([[40., 73., 61., 74., 61., 67., 56., 75., 64., 71., 75., 76., 63.,
        61., 56., 67., 70., 73., 69., 60., 74., 63., 65., 73., 57., 63.,
        66., 69., 60., 66., 72., 71., 57., 64., 64., 69., 67., 68., 59.,
        66., 55., 62., 51., 60.],
       [59., 68., 69., 67., 69., 59., 78., 73., 66., 65., 77., 73., 74.,
        66., 66., 55., 71., 66., 69., 68., 75., 73., 80., 79., 69., 65.,
        69., 66., 68., 65., 75., 71., 59., 61., 65., 64., 73., 71., 81.,
        75., 74., 65., 69., 66.]])

In [433]:
cluster_centroid = np.round(cluster_centroid,2)

In [434]:
cluster_centroid

array([[40., 73., 61., 74., 61., 67., 56., 75., 64., 71., 75., 76., 63.,
        61., 56., 67., 70., 73., 69., 60., 74., 63., 65., 73., 57., 63.,
        66., 69., 60., 66., 72., 71., 57., 64., 64., 69., 67., 68., 59.,
        66., 55., 62., 51., 60.],
       [59., 68., 69., 67., 69., 59., 78., 73., 66., 65., 77., 73., 74.,
        66., 66., 55., 71., 66., 69., 68., 75., 73., 80., 79., 69., 65.,
        69., 66., 68., 65., 75., 71., 59., 61., 65., 64., 73., 71., 81.,
        75., 74., 65., 69., 66.]])

In [435]:
# iterative implementation of k-means

In [436]:
counter = 0

while(1):
    
    counter +=1
    #print(counter)
    
    if counter>1:
        cluster_centroid = new_centroids.copy()
    
    for x in X[:]:
        
        x = x.reshape(1,44)
        
        distance_1 = np.round(distance(x,centroid(c1)),5)
        distance_2 = np.round(distance(x,centroid(c2)),5)

        
        print(distance_1,distance_2)
        
        for i in range(c1.shape[0]):
            if ((c1[i] == x).all()):
                c1 = np.delete(c1,i,0)
                break
            else:
                pass
        
        for i in range(c2.shape[0]):
            if ((c2[i] == x).all()):
                c2 = np.delete(c2,i,0)
                break
            else:
                pass
                
        
        flag = 0
        
        if flag == 0:
            if distance_1 <= distance_2:
                c1 = np.vstack((c1,x))
                flag = 1

        if flag == 0: 
            if distance_2 <= distance_1:
                c2 = np.vstack((c2,x))
                flag = 1
        
    
    
    new_centroids = np.array([centroid(c1),centroid(c2)])
    new_centroids = np.round(new_centroids,5)
    
    
    if counter>1:
        if((new_centroids == cluster_centroid).all()):
            print(True)
            break
    

202.44999 223.23306
111.62213 178.41525
86.14071 93.44517
102.74665 58.5662
114.53547 58.89397
97.16931 51.54178
116.02748 54.39037
87.45785 85.44191
107.72825 39.29801
115.71031 44.89557
90.80129 92.70088
113.14999 57.99744
116.67185 46.14069
94.64206 26.35261
93.91869 46.52006
139.69923 38.60645
124.79333 40.43674
127.98975 30.91735
124.00151 32.58752
146.1861 68.64202
139.1757 37.27565
122.20014 37.25496
128.87348 45.89398
137.18555 33.0983
138.71509 37.89812
126.12246 24.67483
125.57816 38.81856
145.64125 37.03161
141.75463 33.05189
126.94241 32.8237
127.52402 42.37521
138.82498 36.04127
97.46217 60.48541
126.70191 35.18406
105.71601 62.95993
133.55664 32.92248
132.11879 27.07869
115.05814 40.77403
124.46636 44.57152
100.20417 60.84641
111.88331 40.44183
145.71848 37.66492
140.20654 53.70415
129.82247 35.50326
123.45799 26.89705
106.30087 37.63335
92.17036 85.87267
123.91277 37.73365
125.17937 37.31822
132.26819 33.95037
130.62303 51.93547
132.47594 40.65753
122.7696 52.92011
162.6

In [437]:
# final clusters

In [438]:
c1.shape

(12, 44)

In [439]:
c2.shape

(98, 44)

In [440]:
# calculating each cluster's individual accuracy

In [441]:
true_positive = 0
false_positive = 0
for i in range(X.shape[0]):
    if list(X[i]) in c1.tolist():
        if y[i] == 'Yes':
            true_positive+=1
        else:
            false_positive+=1

In [442]:
true_negative = 0
false_negative = 0
for i in range(X.shape[0]):
    if list(X[i]) in c2.tolist():
        if y[i] == 'Yes':
            false_negative+=1
        else:
            true_negative+=1

In [443]:
true_positive

12

In [444]:
false_positive

0

In [445]:
true_negative

55

In [446]:
false_negative

43

In [447]:
accuracy = 100*(true_positive+true_negative)/(true_positive+true_negative+false_positive+false_negative)

In [448]:
accuracy

60.90909090909091

In [179]:
# The distribution of clusters in the compted data

In [180]:
print(y)

['Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No']


In [161]:
# Calculation of final accuracy in percentage