In [1]:
# importing the basic libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
# reading data from the file
#Source: http://archive.ics.uci.edu/ml/datasets/SPECTF+Heart

In [7]:
df = pd.read_csv('SPECTF_test.csv')

In [8]:
df.head()

Attr_1  Attr_2  Attr_3  Attr_4  Attr_5  Attr_6  Attr_7  Attr_8  Attr_9  \
0      32      41      76      34      65      53      30      54      16   
1      76      65      60      40      32      34      65      50      53   
2      60      51      75      60      65      45      64      55      55   
3      64      60      71      69      71      65      66      64      68   
4      65      69      66      76      58      67      65      72      66   

   Attr_10  ...  Attr_36  Attr_37  Attr_38  Attr_39  Attr_40  Attr_41  \
0       51  ...       43       67       61       29       31       17   
1       37  ...       51       65       59       43       39       35   
2       61  ...       68       69       63       62       53       57   
3       59  ...       55       66       58       65       65       75   
4       64  ...       64       71       70       72       69       70   

   Attr_42  Attr_43  Attr_44  Class  
0        8       18       11    Yes  
1       30       24       21    Yes  
2       31       46       30    Yes  
3       64       61       56    Yes  
4       65       63       61    Yes  

[5 rows x 45 columns]

In [9]:
df.tail()

Attr_1  Attr_2  Attr_3  Attr_4  Attr_5  Attr_6  Attr_7  Attr_8  Attr_9  \
105      70      75      72      72      67      71      71      78      63   
106      59      57      67      71      66      68      68      70      56   
107      67      64      73      75      77      77      74      70      65   
108      68      65      72      72      47      74      76      74      67   
109      66      54      69      66      69      69      75      72      63   

     Attr_10  ...  Attr_36  Attr_37  Attr_38  Attr_39  Attr_40  Attr_41  \
105       67  ...       67       68       70       70       71       64   
106       62  ...       64       56       53       71       68       64   
107       62  ...       64       65       60       68       75       74   
108       66  ...       69       71       73       73       75       68   
109       62  ...       65       65       64       67       69       71   

     Attr_42  Attr_43  Attr_44  Class  
105       67       56       54     No  
106       63       56       56     No  
107       80       67       68     No  
108       56       58       44     No  
109       68       59       59     No  

[5 rows x 45 columns]

In [413]:
# identifying the number of categories available

In [10]:
y = df['Class'].values

In [11]:
df['Class'].value_counts()

No     55
Yes    55
Name: Class, dtype: int64

In [12]:
# since there are 2 categories we are going to using k = 2.

In [13]:
y.shape

(110,)

In [14]:
X = df.drop(['Class'],axis = 1).values

In [15]:
X[:10]

array([[32, 41, 76, 34, 65, 53, 30, 54, 16, 51, 61, 43, 74, 70, 62, 21,
        34, 42, 61, 37, 58, 66, 54, 49, 17, 19, 11, 42, 53, 30, 71,  9,
        61, 16, 31, 43, 67, 61, 29, 31, 17,  8, 18, 11],
       [76, 65, 60, 40, 32, 34, 65, 50, 53, 37, 66, 53, 33, 31, 30, 30,
        69, 75, 64, 45, 68, 65, 57, 43, 23, 23, 53, 77, 48, 32, 55, 32,
        48, 23, 62, 51, 65, 59, 43, 39, 35, 30, 24, 21],
       [60, 51, 75, 60, 65, 45, 64, 55, 55, 61, 66, 74, 61, 50, 62, 41,
        70, 63, 60, 62, 76, 69, 70, 54, 51, 47, 77, 80, 69, 48, 74, 59,
        72, 57, 76, 68, 69, 63, 62, 53, 57, 31, 46, 30],
       [64, 60, 71, 69, 71, 65, 66, 64, 68, 59, 63, 67, 68, 64, 73, 59,
        73, 60, 72, 56, 77, 68, 69, 69, 66, 59, 57, 40, 55, 53, 69, 63,
        71, 63, 66, 55, 66, 58, 65, 65, 75, 64, 61, 56],
       [65, 69, 66, 76, 58, 67, 65, 72, 66, 64, 77, 75, 64, 62, 63, 59,
        71, 61, 67, 45, 74, 45, 66, 46, 64, 48, 62, 27, 65, 67, 72, 72,
        62, 66, 71, 64, 71, 70, 72, 69, 70, 65, 63, 

In [20]:
# distance calculator
y.size

110

In [17]:
# distance between 2 points
def distance(p1,p2):
    
    return np.linalg.norm(p1 - p2)

In [18]:
# calculating centroid 

In [41]:
# centroid of a cluster
def centroid(cluster):
    
    length = cluster.shape[0]
    c = [None]*44
    for i in range(44):
        c[i] = np.sum(cluster[:,i])
        c[i] = c[i]/length
    
    
    # c0, c1, c2, c3 = c0/length , c1/length , c2/length , c3/length 
       
    return np.array(c)


In [27]:
df.head()

Attr_1  Attr_2  Attr_3  Attr_4  Attr_5  Attr_6  Attr_7  Attr_8  Attr_9  \
0      32      41      76      34      65      53      30      54      16   
1      76      65      60      40      32      34      65      50      53   
2      60      51      75      60      65      45      64      55      55   
3      64      60      71      69      71      65      66      64      68   
4      65      69      66      76      58      67      65      72      66   

   Attr_10  ...  Attr_36  Attr_37  Attr_38  Attr_39  Attr_40  Attr_41  \
0       51  ...       43       67       61       29       31       17   
1       37  ...       51       65       59       43       39       35   
2       61  ...       68       69       63       62       53       57   
3       59  ...       55       66       58       65       65       75   
4       64  ...       64       71       70       72       69       70   

   Attr_42  Attr_43  Attr_44  Class  
0        8       18       11    Yes  
1       30       24       21    Yes  
2       31       46       30    Yes  
3       64       61       56    Yes  
4       65       63       61    Yes  

[5 rows x 45 columns]

In [28]:
# Assigning random cluster centers initially

In [134]:
c1 = X[10].copy()
c2 = X[51].copy()
c1 = c1.reshape(1,44)
c2 = c2.reshape(1,44)

In [135]:
# cluster 1

In [136]:
c1

array([[76, 59, 82, 76, 80, 56, 74, 67, 67, 58, 77, 71, 56, 68, 60, 64,
        66, 66, 66, 66, 82, 79, 40, 45, 49, 48, 75, 70, 64, 35, 71, 60,
        39, 28, 71, 66, 73, 61, 71, 49, 53, 45, 29, 15]], dtype=int64)

In [137]:
# cluster 2

In [138]:
c2

array([[70, 65, 65, 62, 68, 67, 77, 74, 62, 61, 66, 61, 69, 74, 64, 62,
        71, 71, 74, 70, 77, 78, 69, 70, 67, 65, 67, 70, 49, 48, 73, 71,
        65, 73, 73, 73, 75, 71, 73, 72, 73, 70, 65, 64]], dtype=int64)

In [139]:
print(X)


[[32 41 76 ...  8 18 11]
 [76 65 60 ... 30 24 21]
 [60 51 75 ... 31 46 30]
 ...
 [67 64 73 ... 80 67 68]
 [68 65 72 ... 56 58 44]
 [66 54 69 ... 68 59 59]]


In [140]:
# centroids for each cluster

In [141]:
centroid_1 = centroid(c1)
centroid_2 = centroid(c2)

In [142]:
centroid_1

array([76., 59., 82., 76., 80., 56., 74., 67., 67., 58., 77., 71., 56.,
       68., 60., 64., 66., 66., 66., 66., 82., 79., 40., 45., 49., 48.,
       75., 70., 64., 35., 71., 60., 39., 28., 71., 66., 73., 61., 71.,
       49., 53., 45., 29., 15.])

In [143]:
centroid_2

array([70., 65., 65., 62., 68., 67., 77., 74., 62., 61., 66., 61., 69.,
       74., 64., 62., 71., 71., 74., 70., 77., 78., 69., 70., 67., 65.,
       67., 70., 49., 48., 73., 71., 65., 73., 73., 73., 75., 71., 73.,
       72., 73., 70., 65., 64.])

In [144]:
# making a numpy array for all the clusters for futher calculations

In [145]:
cluster_centroid = np.array([centroid_1,centroid_2])

In [146]:
cluster_centroid

array([[76., 59., 82., 76., 80., 56., 74., 67., 67., 58., 77., 71., 56.,
        68., 60., 64., 66., 66., 66., 66., 82., 79., 40., 45., 49., 48.,
        75., 70., 64., 35., 71., 60., 39., 28., 71., 66., 73., 61., 71.,
        49., 53., 45., 29., 15.],
       [70., 65., 65., 62., 68., 67., 77., 74., 62., 61., 66., 61., 69.,
        74., 64., 62., 71., 71., 74., 70., 77., 78., 69., 70., 67., 65.,
        67., 70., 49., 48., 73., 71., 65., 73., 73., 73., 75., 71., 73.,
        72., 73., 70., 65., 64.]])

In [147]:
cluster_centroid = np.round(cluster_centroid,2)

In [148]:
cluster_centroid

array([[76., 59., 82., 76., 80., 56., 74., 67., 67., 58., 77., 71., 56.,
        68., 60., 64., 66., 66., 66., 66., 82., 79., 40., 45., 49., 48.,
        75., 70., 64., 35., 71., 60., 39., 28., 71., 66., 73., 61., 71.,
        49., 53., 45., 29., 15.],
       [70., 65., 65., 62., 68., 67., 77., 74., 62., 61., 66., 61., 69.,
        74., 64., 62., 71., 71., 74., 70., 77., 78., 69., 70., 67., 65.,
        67., 70., 49., 48., 73., 71., 65., 73., 73., 73., 75., 71., 73.,
        72., 73., 70., 65., 64.]])

In [149]:
# iterative implementation of k-means

In [150]:
counter = 0

while(1):
    
    counter +=1
    #print(counter)
    
    if counter>1:
        cluster_centroid = new_centroids.copy()
    
    for x in X[:]:
        
        x = x.reshape(1,44)
        
        distance_1 = np.round(distance(x,centroid(c1)),5)
        distance_2 = np.round(distance(x,centroid(c2)),5)

        
        print(distance_1,distance_2)
        
        for i in range(c1.shape[0]):
            if ((c1[i] == x).all()):
                c1 = np.delete(c1,i,0)
                break
            else:
                pass
        
        for i in range(c2.shape[0]):
            if ((c2[i] == x).all()):
                c2 = np.delete(c2,i,0)
                break
            else:
                pass
                
        
        flag = 0
        
        if flag == 0:
            if distance_1 <= distance_2:
                c1 = np.vstack((c1,x))
                flag = 1

        if flag == 0: 
            if distance_2 <= distance_1:
                c2 = np.vstack((c2,x))
                flag = 1
        
    
    
    new_centroids = np.array([centroid(c1),centroid(c2)])
    new_centroids = np.round(new_centroids,5)
    
    
    if counter>1:
        if((new_centroids == cluster_centroid).all()):
            print(True)
            break
    

181.29534 221.58745
100.60815 172.66152
94.8859 94.49868
132.39084 56.06692
143.67092 66.66667
124.1679 50.15476
149.09393 52.86889
107.26913 77.45142
135.48186 45.14195
146.5617 46.38359
93.14684 87.42687
184.51219 60.5062
188.67631 51.60058
168.37681 28.6183
167.17581 48.18081
193.65627 44.32872
177.52394 40.94831
181.70237 33.99035
176.8071 35.01354
191.916 71.96885
192.89051 40.90578
178.03019 35.853
179.4401 47.19036
189.89142 36.88669
190.63775 41.55214
181.49311 25.6147
181.00483 38.29717
200.38151 40.47534
193.94265 37.11743
182.14211 32.82394
176.81275 43.54199
192.79977 37.72733
155.86132 56.27699
175.68651 37.40737
153.33542 61.07672
184.6016 35.57073
185.7976 28.55585
167.93674 39.58167
172.10099 45.63135
151.67317 58.85994
165.5891 39.03123
198.09278 40.20594
194.63491 54.03716
180.65367 36.76959
178.46218 26.57484
160.77235 36.12837
139.75246 83.90658
174.81061 38.30849
178.02177 37.46929
185.4663 34.95737
180.90813 52.16962
185.39889 40.62377
173.95042 52.75804
161.78303

In [151]:
# final clusters

In [152]:
c1.shape

(6, 44)

In [153]:
c2.shape

(104, 44)

In [154]:
# calculating each cluster's individual accuracy

In [155]:
true_positive = 0
false_positive = 0
for i in range(X.shape[0]):
    if list(X[i]) in c1.tolist():
        if y[i] == 'Yes':
            true_positive+=1
        else:
            false_positive+=1

In [156]:
true_negative = 0
false_negative = 0
for i in range(X.shape[0]):
    if list(X[i]) in c2.tolist():
        if y[i] == 'Yes':
            false_negative+=1
        else:
            true_negative+=1

In [157]:
true_positive

6

In [158]:
false_positive

0

In [159]:
true_negative

55

In [160]:
false_negative

49

In [88]:
# The distribution of clusters in the compted data

In [89]:
print(y)

['Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No']


In [161]:
# Calculation of final accuracy in percentage