In [68]:
# importing the basic libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [73]:
# reading data from the file
#Source: http://archive.ics.uci.edu/ml/datasets/Iris

In [6]:
df = pd.read_csv('iris.data', header=None)

In [7]:
df.head()

0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

In [8]:
# addin column names 

In [9]:
df.columns = ['sepal_length','sepal_width','petal_length','petal_width','Species']

In [10]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [11]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [12]:
df.tail()

sepal_length  sepal_width  petal_length  petal_width         Species
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

In [413]:
# identifying the number of categories available

In [13]:
y = df['Species'].values

In [14]:
df['Species'].value_counts()

Iris-versicolor    50
Iris-setosa        50
Iris-virginica     50
Name: Species, dtype: int64

In [15]:
# since there are 3 categories we are going to using k = 3.

In [16]:
y.shape

(150,)

In [17]:
X = df.drop(['Species'],axis = 1).values

In [18]:
X[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [19]:
# distance calculator

In [20]:
# distance between 2 points
def distance(p1,p2):
    
    return np.linalg.norm(p1 - p2)

In [21]:
# calculating centroid 

In [22]:
# centroid of a cluster
def centroid(cluster):
    
    length = cluster.shape[0]
    
    c0 = np.sum(cluster[:,0])
    c1 = np.sum(cluster[:,1])
    c2 = np.sum(cluster[:,2])
    c3 = np.sum(cluster[:,3])
    
    c0, c1, c2, c3 = c0/length , c1/length , c2/length , c3/length 
       
    return np.array([c0,c1,c2,c3])

In [23]:
df.head()

sepal_length  sepal_width  petal_length  petal_width      Species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [24]:
# Assigning random cluster centers initially

In [25]:
c1 = X[113].copy()
c2 = X[39].copy()
c3 = X[61].copy()
c1 = c1.reshape(1,4)
c2 = c2.reshape(1,4)
c3 = c3.reshape(1,4)

In [26]:
# cluster 1

In [27]:
c1

array([[5.7, 2.5, 5. , 2. ]])

In [28]:
# cluster 2

In [29]:
c2

array([[5.1, 3.4, 1.5, 0.2]])

In [30]:
# cluster 3

In [31]:
c3

array([[5.9, 3. , 4.2, 1.5]])

In [32]:
# centroids for each cluster

In [33]:
centroid_1 = centroid(c1)
centroid_2 = centroid(c2)
centroid_3 = centroid(c3)

In [34]:
centroid_1

array([5.7, 2.5, 5. , 2. ])

In [35]:
centroid_2

array([5.1, 3.4, 1.5, 0.2])

In [36]:
centroid_3


array([5.9, 3. , 4.2, 1.5])

In [37]:
# making a numpy array for all the clusters for futher calculations

In [38]:
cluster_centroid = np.array([centroid_1,centroid_2,centroid_3])

In [39]:
cluster_centroid

array([[5.7, 2.5, 5. , 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.9, 3. , 4.2, 1.5]])

In [40]:
cluster_centroid = np.round(cluster_centroid,2)

In [41]:
cluster_centroid

array([[5.7, 2.5, 5. , 2. ],
       [5.1, 3.4, 1.5, 0.2],
       [5.9, 3. , 4.2, 1.5]])

In [42]:
# iterative implementation of k-means

In [43]:
counter = 0

while(1):
    
    counter +=1
    #print(counter)
    
    if counter>1:
        cluster_centroid = new_centroids.copy()
    
    for x in X[3:]:
        
        x = x.reshape(1,4)
        
        distance_1 = np.round(distance(x,centroid(c1)),2)
        distance_2 = np.round(distance(x,centroid(c2)),2)
        distance_3 = np.round(distance(x,centroid(c3)),2)
        
        #print(distance_1,distance_2,distance_3)
        
        for i in range(c1.shape[0]):
            if ((c1[i] == x).all()):
                c1 = np.delete(c1,i,0)
                break
            else:
                pass
        
        for i in range(c2.shape[0]):
            if ((c2[i] == x).all()):
                c2 = np.delete(c2,i,0)
                break
                
        for i in range(c3.shape[0]):
            if ((c3[i] == x).all()):
                c3 = np.delete(c3,i,0)
                break
        
        flag = 0
        
        if flag == 0:
            if distance_1 <= distance_2 and distance_1 <= distance_3:
                c1 = np.vstack((c1,x))
                flag = 1

        if flag == 0: 
            if distance_2 <= distance_3 and distance_2 <= distance_1:
                c2 = np.vstack((c2,x))
                flag = 1
        
        if flag == 0:
            if distance_3 <= distance_1 and distance_3 <= distance_2:
                c3 = np.vstack((c3,x))
                flag = 1
    
    
    new_centroids = np.array([centroid(c1),centroid(c2),centroid(c3)])
    new_centroids = np.round(new_centroids,2)
    
    
    if counter>1:
        if((new_centroids == cluster_centroid).all()):
            #print(True)
            break
    

In [44]:
# final clusters

In [45]:
c1.shape

(60, 4)

In [46]:
c2.shape

(45, 4)

In [47]:
c3.shape 

(39, 4)

In [49]:
# calculating each cluster's individual accuracy

In [58]:
miss_1 = 0
for i in range(X.shape[0]):
    if list(X[i]) in c1.tolist():
        if y[i] != 'Iris-versicolor':
            miss_1+=1

In [59]:
miss_1

14

In [60]:
miss_2 = 0
for i in range(X.shape[0]):
    if list(X[i]) in c2.tolist():
        if y[i] != 'Iris-setosa':
            miss_2+=1

In [61]:
miss_2

0

In [62]:
miss_3 = 0
for i in range(X.shape[0]):
    if list(X[i]) in c3.tolist():
        if y[i] != 'Iris-virginica':
            miss_3+=1

In [63]:
miss_3

3

In [74]:
# The distribution of clusters in the compted data

In [72]:
print(y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor

In [75]:
# Calculation of final accuracy in percentage

In [76]:
accuracy = (1 - (miss_1 + miss_2 + miss_3 )/ 150) * 100

In [77]:
accuracy

88.66666666666667